Updated deploy script to handle single locale

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -1,33 +1,42 @@
 #!/bin/bash
 
-cd $(dirname $0)
+## Usage:
+##
+##  deploy                 # deploy all locales
+##  deploy <locale>        # deploy single locale
+
+cd "$(dirname $0)"
+
+LOCALE="$1"
 
 #######################################################
-# Building locale: EN
 
-bundle exec middleman build -e en
+if [ -z "$LOCALE" ] || [ "$LOCALE" = "en" ]; then
+  bundle exec middleman build -e en
 
-if [ $? -ne 0 ]; then
-  echo "Build failed for locale 'en' (skipping deployment)."
-  exit 1
+  if [ $? -ne 0 ]; then
+    echo "Build failed for locale 'en' (skipping deployment)."
+    exit 1
+  fi
+
+  # www.learningspaces.io.s3-website.eu-central-1.amazonaws.com
+  echo "Deploying to Amazon S3 (www.learningspaces.io) ..."
+  aws s3 sync build/ s3://www.learningspaces.io/ --region=eu-central-1 --acl=public-read --delete --cache-control="max-age=1576800000" --exclude "*.html"
+  aws s3 sync build/ s3://www.learningspaces.io/ --region=eu-central-1 --acl=public-read --delete --cache-control="max-age=0, no-cache" --exclude "*" --include "*.html"
 fi
-
-# www.learningspaces.io.s3-website.eu-central-1.amazonaws.com
-echo "Deploying to Amazon S3 (www.learningspaces.io) ..."
-aws s3 sync build/ s3://www.learningspaces.io/ --region=eu-central-1 --acl=public-read --delete --cache-control="max-age=1576800000" --exclude "*.html"
-aws s3 sync build/ s3://www.learningspaces.io/ --region=eu-central-1 --acl=public-read --delete --cache-control="max-age=0, no-cache" --exclude "*" --include "*.html"
 
 #######################################################
-# Building locale: NL
 
-bundle exec middleman build -e nl
+if [ -z "$LOCALE" ] || [ "$LOCALE" = "nl" ]; then
+  bundle exec middleman build -e nl
 
-if [ $? -ne 0 ]; then
-  echo "Build failed for locale 'nl' (skipping deployment)."
-  exit 1
+  if [ $? -ne 0 ]; then
+    echo "Build failed for locale 'nl' (skipping deployment)."
+    exit 1
+  fi
+
+  # www.learningspaces.nl.s3-website.eu-central-1.amazonaws.com
+  echo "Deploying to Amazon S3 (www.learningspaces.nl) ..."
+  aws s3 sync build/ s3://www.learningspaces.nl/ --region=eu-central-1 --acl=public-read --delete --cache-control="max-age=1576800000" --exclude "*.html"
+  aws s3 sync build/ s3://www.learningspaces.nl/ --region=eu-central-1 --acl=public-read --delete --cache-control="max-age=0, no-cache" --exclude "*" --include "*.html"
 fi
-
-# www.learningspaces.nl.s3-website.eu-central-1.amazonaws.com
-echo "Deploying to Amazon S3 (www.learningspaces.nl) ..."
-aws s3 sync build/ s3://www.learningspaces.nl/ --region=eu-central-1 --acl=public-read --delete --cache-control="max-age=1576800000" --exclude "*.html"
-aws s3 sync build/ s3://www.learningspaces.nl/ --region=eu-central-1 --acl=public-read --delete --cache-control="max-age=0, no-cache" --exclude "*" --include "*.html"
